version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - run: apt-get update; apt-get -y install nghttp2
      - checkout
      - run: swift build
      - run: swift test
  linux-release:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - run: apt-get update; apt-get -y install nghttp2
      - checkout
      - run: swift build -c release
workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
