name: test
on:
- pull_request
jobs:
  focal:
    container:
      image: swift:5.6-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery